local/urls.py
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView


# Below are the 'recommended' locations for the paths to aristotle extensions.
urlpatterns = [
    url(r'^about/?$', TemplateView.as_view(template_name='static/about.html'), name="about"),
    url(r'^contact/?$', TemplateView.as_view(template_name='static/contact.html'), name="contact"),
    url(r'^terms_of_use/?$', TemplateView.as_view(template_name='static/terms_of_use.html'), name="terms_of_use"),
    url(r'^privacy/?$', TemplateView.as_view(template_name='static/privacy.html'), name="privacy"),
]

if settings.DEBUG:
    from .views import *

    urlpatterns += [
        url(r'^500/$', handler500),
        url(r'^404/$', handler404),
    ]

logicaloutcomes/urls.py
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url


# Below are the 'recommended' locations for the paths to aristotle extensions.
# At this point the 'glossary' extension *requires* being in the root at `/glossary/`.
urlpatterns = patterns(
    '',
    url(r'^', include('local.urls')),
    url(r'^', include('indicators.urls')),
    url(r'^', include('aristotle_mdr.urls')),
    url(r'^ddi/', include('aristotle_ddi_utils.urls', app_name="aristotle_ddi_utils", namespace="aristotle_ddi_utils")),
    url(r'^dse/', include('aristotle_dse.urls', app_name="aristotle_dse", namespace="aristotle_dse")),
    url(r'^comet/', include('comet.urls', app_name="comet", namespace="comet")),
    url(r'^mallard/', include('mallard_qr.urls', app_name="mallard_qr", namespace="mallard_mdr")),
    url(r'^api/', include('aristotle_mdr_api.urls', app_name="aristotle_mdr_api", namespace="aristotle_mdr_api")),

    # Auth views
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': '/user/password/done/'},
        name='password_reset_confirm',),
    url(r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'),

    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
)

handler404 = 'local.views.handler404'
handler500 = 'local.views.handler500'
handler403 = 'local.views.handler403'
handler400 = 'local.views.handler400'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

sis_sites/ocasi/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from sis_sites.ocasi.views import BrowseRegistry, MyWorkspaceView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='sis_sites/ocasi/home.html'), name="ocasi_home"),
    url(r'^help/$', TemplateView.as_view(template_name='sis_sites/ocasi/help.html'), name="ocasi_help"),
    url(r'^data-portal/$', TemplateView.as_view(template_name='sis_sites/ocasi/data_portal.html'), name="ocasi_data_portal"),

    url(r'^evaluation/$', TemplateView.as_view(template_name='sis_sites/ocasi/evaluation.html'), name="ocasi_evaluation"),
    url(r'^evaluation/create-logic-model/$', TemplateView.as_view(template_name='sis_sites/ocasi/create_logic_model.html'), name="ocasi_create_logic_model"),
    url(r'^evaluation/design-evaluation-plan/$', TemplateView.as_view(template_name='sis_sites/ocasi/evaluation_plan.html'), name="ocasi_evaluation_plan"),
    url(r'^evaluation/review-data-collection-tools/$', TemplateView.as_view(template_name='sis_sites/ocasi/review_data_collection_tools.html'), name="ocasi_review_data_collection_tools"),

    url(r'^registry/$', BrowseRegistry.as_view(), name="ocasi_registry"),
    url(r'^my-workspace/$', MyWorkspaceView.as_view(), name="ocasi_my_workspace"),

    url(r'^', include('logicaloutcomes.urls')),
]

sis_sites/urls.py
from django.conf.urls import url, include


urlpatterns = [
    # OCASI urls
    url(r'^', include('sis_sites.ocasi.urls')),
]

local/models.py
from django.db import models

# Create your models here.

sis_sites/models.py
from django.db import models
from django.template import Template, Context


class Snippet(models.Model):
    name = models.CharField(max_length=128)
    content = models.TextField()

    class Meta:
        verbose_name_plural = 'Snippets'

    def __unicode__(self):
        return self.name


class ContentBlock(models.Model):
    snippet = models.ForeignKey(Snippet)
    page = models.ForeignKey('flatpages.FlatPage')
    content = models.TextField(blank=True, null=True)
    value = models.TextField(blank=True, null=True)
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Content Blocks'
        ordering = ['order']

    def __unicode__(self):
        return u"{} - {}".format(self.snippet.name, self.order)

    def render(self):
        template = Template(self.snippet.content)
        context = Context({
            'content': self.content,
            'value': self.value,
        })
        return template.render(context)

local/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response


def handler403(request):
    response = render_to_response('403.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler400(request):
    response = render_to_response('400.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 400
    return response

sis_sites/ocasi/views.py
# from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView
from indicators.views import BrowseIndicatorsAsHome


class BrowseRegistry(BrowseIndicatorsAsHome):
    template_name = 'sis_sites/ocasi/registry.html'

    def get_template_names(self):
        return [self.template_name]


class MyWorkspaceView(TemplateView):
    template_name = 'sis_sites/ocasi/my_workspace.html'


# class MyWorkspaceView(RedirectView):

#     permanent = False
#     query_string = True

#     def get_redirect_url(self, *args, **kwargs):
#         return 'https://reports.ocasi.sis.ngo'

sis_sites/views.py
from django.shortcuts import render

# Create your views here.

local/templates/aristotle_mdr/footer.html
{% load static i18n %}
<footer class="lo-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <div class="col-xs-6">
                        <img class="lo-footer_logo" src="{% static "img/logicaloutcomes_reverse.jpg" %}" alt="LogicalOutcomes" width="130">
                    </div>
                    <div class="col-xs-6">
                        <p>{% trans "Find us on" %}</p>
                        <p class="lo-footer_social">
                            <a href="https://twitter.com/logical_info">
                                <i class="fa fa-twitter fa-2x"></i>
                            </a>
                            <a href="http://www.linkedin.com/company/logicaloutcomes">
                                <i class="fa fa-linkedin fa-2x"></i>
                            </a>
                            <a href="https://www.youtube.com/channel/UCb2lXqTIo-81NekAEVDt5bw">
                                <i class="fa fa-youtube fa-2x"></i>
                            </a>
                            <a href="http://logicaloutcomes.net/feed/">
                                <i class="fa fa-rss fa-2x"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xs-6">
                <ul>
                    <li>
                        <a href="/about/">{% trans "About" %}</a>
                    </li>
                    <li>
                        <a href="/contact/">{% trans "Contact" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'aristotle:accessibility' %}">{% trans "Accessibility" %}</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 col-xs-6">
                <ul>
                    <li>
                        <a href="/privacy/">{% trans "Privacy" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'aristotle_help:help_base' %}">{% trans 'Help'%}</a>
                    </li>
                    <li>
                        <a href="/terms_of_use/">{% trans "Terms of Use and Disclaimer" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <p class="credits">{% trans "© LogicalOutcomes 2017" %}</p>
            </div>

            <div class="col-md-8">
                <p class="credits">
                    {# Removing or altering the following line may breach your licence #}
                    {# If you extend this file make sure the following link is retained in your footer #}
                    <span id="credit">
                        Powered by <a href="http://logicaloutcomes.net/">LogicalOutcomes</a> and the <a href="http://aristotlemetadata.com">Aristotle Metadata Registry</a>
                    </span>
                </p>
            </div>
        </div>
    </div>
</footer>

local/templates/aristotle_mdr/header.html
{% load i18n %}
{% load notifications_tags %}
<a class="sr-only" accesskey="j" href="#content">Skip to content</a>
<a class="sr-only" accesskey="l" href="{% url 'aristotle:accessibility' %}#accesskeys">Learn about the access keys available for {{ config.SITE_NAME }}</a>
<nav class="main navbar navbar-default">
<div class="container-fluid" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'aristotle:home' %}" id="logo">
        <img height="40px" src="{{ config.SITE_BRAND }}" alt="{{ config.SITE_NAME }}" title="{{ config.SITE_NAME }}">
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% if not hide_search %}
            {% comment %}
            The search block is defined to allow some pages
            (SPECIFICALLY the home page) to override or hide the search bar
            DO NOT OVERRIDE THIS UNLESS YOU ARE CERTAIN OF WHAT YOU ARE DOING!
            {% endcomment %}
            <form id="quickSearch" action="{% url 'aristotle:search' %}" method="get"
            class="navbar-form navbar-left" role="search">
                <label style="display:none;" for="searchText">Search:</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="searchText" name="q" accesskey="q"
                    placeholder="Search the registry"></input>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit" title="{% trans 'Search' %}">
                            <i class="fa fa-search"></i>&nbsp;
                        </button>
                    </span>
                </div>
            </form>
        {% endif %}

        <ul class="nav navbar-nav navbar-right">
            <li class="{% if request.path == '/' %}active{% endif %}">
                <a href="/">{% trans "Browse Indicators" %}</a>
            </li>
            {% url 'comparer' as comparer_url %}
            <li class="{% if request.path == comparer_url %}active{% endif %}">
                <a href="{{comparer_url}}">{% trans "Compare Indicators" %}</a>
            </li>
            {% url 'exporter' as exporter_url %}
            <li class="{% if request.path == '/content/export/' %}active{% endif %}">
                <a href="/content/export/">{% trans "Export" %}</a>
            </li>
            {% comment %}
            <li >
                <a href="{% url 'comparer' %}">Compare indicators</a>
            </li>
            <li >
                <a href="{% url 'aristotle:userHome' %}">Your portfolio</a>
            </li>
            {% endcomment %}
        {% if user.is_active %}
            <li class="dropdown">
                <a href="{% url 'aristotle:userHome' %}" accesskey="u" class="dropdown-toggle" role="menu" data-toggle="dropdown" title="{% trans 'Open user menu' %}">
                    {% if user.is_superuser %}
                        <i class="fa fa-user-md fa-lg"></i>
                    {% else %}
                        <i class="fa fa-user fa-lg"></i>
                    {% endif %}
                    {% firstof user.get_short_name user.get_username %}
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'aristotle:userHome' %}">
                        <i class="fa fa-home fa-fw"></i> {% trans 'My Dashboard'%}
                    </a></li>
                    <li><a href="{% url 'aristotle:userFavourites' %}">
                        <i class="fa fa-bookmark fa-fw"></i> {% trans 'My Favourites'%}
                        <span class="badge pull-right">{{ user.profile.favourites.count }}</span>
                    </a></li>
                    <li><a href="{% url 'aristotle:userInbox' %}">
                        <i class="fa fa-envelope fa-fw"></i> {% trans 'Notifications'%}
                        {% with notecount=user.notifications.unread.count %}
                        <span class="badge pull-right" title="{{ notecount }} unread notifications">{{ notecount }}</span>
                        {% endwith %}
                    </a></li>
                    <li><a href="{% url 'aristotle:discussions' %}">
                        <i class="fa fa-comments fa-fw"></i> {% trans 'Discussions'%}
                    </a></li>
                    <li><a href="{% url 'aristotle:userWorkgroups' %}">
                        <i class="fa fa-users fa-fw"></i> {% trans 'Workgroups'%}
                    </a></li>
                    <li><a href="{% url 'aristotle:userRecentItems' %}">
                        <i class="fa fa-history fa-fw"></i> {% trans 'Recent actions'%}
                    </a></li>
                    {% if user.has_usable_password %}
                        <li><a href="{% url 'password_change' %}">
                        <i class="fa fa-cog fa-fw"></i> {% trans 'Change password' %}
                        </a></li>
                    {% endif %}
                    {% if user.profile.is_registrar %}
                        <li role="presentation" class="divider"></li>
                        <li><a href="{% url 'aristotle:userRegistrarTools' %}">
                        <i class="fa fa-university fa-fw"></i> {% trans 'Registrar tools' %}
                        </a></li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li role="presentation" class="divider"></li>
                        <li><a class="staff_action" href="{% url 'admin:index' %}">
                        <i class="fa fa-sliders fa-fw"></i> {% trans 'Management interface' %}
                        </a></li>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <li><a class="su_action" href="{% url 'aristotle:userAdminTools' %}">
                        <i class="fa fa-user-md fa-fw"></i> {% trans 'Admin tools' %}
                        </a></li>
                    {% endif %}
                </ul>
            </li>
            <li class="dropdown">
                <a href="{% url 'aristotle:create_list' %}"
                    accesskey="o" class="dropdown-toggle" data-toggle="dropdown" title="{% trans 'Create new' %}...">
                    <i class="fa fa-plus"></i>
                    <span class="visible-xs-inline">{% trans 'Create new' %} ... </span>
                    <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu" role="menu" >
                    <li><a href="{% url 'aristotle:createItem' 'aristotle_mdr' 'objectclass'%}">Object Class</a></li>
                    <li><a href="{% url 'aristotle:createItem' 'aristotle_mdr' 'property'%}">Property</a></li>
                    <li><a href="{% url 'aristotle:createItem' 'aristotle_mdr' 'valuedomain'%}">Value Domain</a></li>
                    <li><a href="{% url 'aristotle:createItem' 'aristotle_mdr' 'dataelementconcept'%}">Data Element Concept</a></li>
                    <li><a href="{% url 'aristotle:createItem' 'aristotle_mdr' 'dataelement'%}">Data Element</a></li>
                    {# <li><a href="{% url 'aristotle:createDataElement'%}"></a></li> #}

                    {% if request.user.is_superuser %}
                        <li role="presentation" class="divider"></li>
                        <li role="presentation" class="dropdown-header">
                            <i class="fa fa-user-md fa-2x"></i> {% trans 'Admin only' %}
                        </li>
                        <li>
                            <a class="su_action" href="{% url 'admin:aristotle_mdr_workgroup_add'%}">
                                <i class="fa fa-users fa-fw"></i> {% trans 'Workgroup' %}</a>
                        </li>
                        <li>
                            <a class="su_action" href="{% url 'admin:auth_user_add'%}">
                                <i class="fa fa-user-plus fa-fw"></i> {% trans 'User' %}
                            </a>
                        </li>
                    {% endif %}
                    <li role="presentation" class="divider"></li>
                    <li>
                        <a href="{% url 'aristotle:create_list' %}">{% trans 'See all'%}...</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="{% url 'notifications:all' %}"
                    class="dropdown-toggle" data-toggle="dropdown" title="{% trans 'Show recent notifications' %}">
                    {% if user.notifications.unread %}
                    <span class="notify" title="{% trans 'New notifications' %}"></span>
                    <span class="visible-xs-inline">{% trans 'New notifications' %}</span>
                    {% else %}
                    <span class="no-notify" title="{% trans 'No unread notifications' %}"></span>
                    <span class="visible-xs-inline">{% trans 'No unread notifications' %}</span>
                    {% endif %}
                    {% live_notify_badge classes="badge" %}
                </a>
                {% live_notify_list classes="dropdown-menu" %}
            </li>
            <li>
                <a href="{% url 'django.contrib.auth.views.logout' %}?next={{request.path}}" title="{% trans 'Log out'%}">
                    <i class="fa fa-sign-out fa-fw"></i>
                    <span class="visible-xs-inline">{% trans 'Log out' %}</span>
                </a>
            </li>
        {% else %}
            <li >
                <a href="{% url 'friendly_login' %}">{% trans 'Log in'%}</a>
            </li>
        {% endif %}
            <li >
                <a accesskey="h" href="{% url 'aristotle_help:help_base' %}">{% trans 'Help'%}</a>
            </li>
        </ul>
    </div>
</div>
</nav>

local/templates/local/downloads/pdf/bulk_download.html
{% load i18n aristotle_help aristotle_tags %}

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <title>{% block title %}{{ title }}{% endblock %} - {{ config.SITE_NAME }}</title>
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <style type="text/css">
            * {
                font-size:11pt;
            }
            h1 {
                border-bottom:1px solid black;
                padding:5px;
            }
            h2 {
                padding:5px;
                -pdf-outline: false;
            }
            h3 {
                -pdf-outline: false;
            }
            #footerContent, #footerContent * {
                font-size:8pt;
            }
            #supersedes {
                list-style-type:none;
                margin-left:0px;
                float:right;
            }
            #supersedes > span {
                display:table-cell;
            }
            #supersedes ul, #supersedes ol {
                display:inline-block;
                list-style-type:none;
                padding:0px;
                margin:0px;
            }
            #content .objectSpecific dl {
                padding-top:0.25cm;
                padding-left:0.5cm;
            }
            #content .objectSpecific dt {
                font-weight:bold;
            }
            #content .objectSpecific dd {
                padding-left:1cm;
            }
            a {
                text-decoration: none;
                color:black;
                padding-left:1px;
            }
            pdftoc {
                color: #444;
            }
            pdftoc.pdftoclevel0 {
                font-weight: bold;
                margin-top: 0.5em;
                border-bottom:1px solid black;
                text-decoration:underline;
            }
            pdftoc.pdftoclevel1 {
                margin-left: 1em;
                border-bottom:1px solid black;
                text-decoration:underline;
            }
            pdftoc.pdftoclevel2 {
                margin-left: 2em;
                border-bottom:1px solid black;
            }
            td, td * , th, th *{
                vertical-align:top;
            }
            cite {
                font-style:italic;
            }
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                margin-bottom: 2cm;
                padding: 0.5cm;
                border: 0px solid white;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 2cm;
                    margin-right: 2cm;
                    padding:0.2cm;
                    height: 2cm;
                }
            }
       </style>
   </head>
   <body>
   <div id="main">
       <div style="page-break-after:always;">
           <h1 style="-pdf-outline: false;">Table of contents</h1>
           <pdf:toc />
       </div>

       <div id='content'>
            {% for t,dict in included_items %}
                {% with object=dict.help %}
                    {% if object %}
                    <p>
                        <strong>Definition:</strong>
                        {% relink object 'brief' %}
                    </p>
                    <p>
                        For more information see the <em>Glossary of included metadata types</em>.
                    </p>
                    {% endif %}
                {% endwith %}
                {% for item in dict.qs.all %}
                    <div style="page-break-after:always;">
                        {% include "local/downloads/pdf/indicator_content.html" with item=item.item %}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
    <div id="footerContent">
        {%block page_foot%}
            Page <pdf:pagenumber>
        {%endblock%}
        <br/>
        <footer>
        LogicalOutcomes IndicatorRegistry.net {% now 'Y-m-d' %} -
        Powered by the Aristotle Metadata Registry
        </footer>
    </div>
   </body>
</html>

local/templates/local/downloads/pdf/data_element_simple_display.html
<p>
    {% include "local/downloads/pdf/slot_simple_display.html" with name='Form name' hide_title=True%}
    <span style="font-size: 8pt;">
        {% comment %}
            ({{item.valueDomain.name}})
            {% include "aristotle_mdr/helpers/itemLink.html" with item=item.valueDomain %}
        {% endcomment %}
    </span>
</p>

{% comment %}
{% if item.valueDomain.permissibleValues.count > 0 %}
    <table class="codeList table table-striped">
        <thead>
            <tr>
                <th align="right" style="padding-right:5px">Value</th>
                <th align="left" style="padding-left:5px">Meaning</th>
            </tr>
        </thead>
        <tbody>
        {% for perm in item.valueDomain.permissibleValues.all %}
            <tr>
                <td align="right" style="padding-right:5px">{{ perm.value }}</td>
                <td style="padding-left:5px">{{ perm.meaning }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<br>
{% endif %}


{% include "aristotle_mdr/downloads/pdf/inline/valueDomainRepresentation.html" with item=item.valueDomain %}

{% endcomment %}

local/templates/local/downloads/pdf/indicator.html
{% extends 'local/downloads/pdf/pdf.html' %}
{% load aristotle_tags aristotle_help %}

{% block title %}{{ item.name }}{% endblock %}
{% block content %}
{% include "local/downloads/pdf/indicator_content.html" %}

{% endblock %}

local/templates/local/downloads/pdf/indicator_content.html
<section>
<header>
    <h1>
        {{ item.name }}
    </h1>
</header>

{{ item.definition|safe }}

<div class="objectSpecific">
    {% include "local/downloads/pdf/property_simple_display.html" with name='Numerator description' prop=item.numerator_description %}

    <h2>Indicator calculation</h2>
    Numerator: {{ item.numerator_computation }}
    <br>
    Denominator: {{ item.denominator_computation }}

    {% include "local/downloads/pdf/property_simple_display.html" with name='Rationale' prop=item.rationale %}

    {% include "local/downloads/pdf/property_simple_display.html" with name='References' prop=item.references %}

    {% include "local/downloads/pdf/property_simple_display.html" with name='Additional information' prop=item.comments %}

    <h2 class="compact">Logic model</h2>
    {% include "local/downloads/pdf/slot_simple_display.html" with name='Inputs and outputs' display='inline' hide_title=True next_slot='Outcomes' %}
    {% include "local/downloads/pdf/slot_simple_display.html" with name='Outcomes' display='inline' hide_title=True %}

    <h2 class="loose">Indicator registry URL</h2>
    <a href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{{ item.get_absolute_url }}">
        {{ request.scheme }}://{{ request.META.HTTP_HOST }}{{ item.get_absolute_url }}
    </a>

</div>


</section>

local/templates/local/downloads/pdf/property_simple_display.html
{% comment %}
Usage: {% include "local/downloads/pdf/property_simple_display.html" with item=obj name='Reference' prop='references' %}
{% endcomment %}
{% if prop %}
    <h2>{{ name }}</h2>
    <p>{{ prop|safe }}</p>
{% endif %}

local/templates/local/downloads/pdf/slot_simple_display.html
{% load aristotle_tags slot_tags markdown_deux_tags %}
{% comment %}
Usage: {% include "local/downloads/pdf/slot_simple_display.html" with item=obj name='Reference' display='inline' hide_title=True %}
{% endcomment %}
{% with item|slots_by_type:name as slots %}
    {% if slots %}
        {% if not hide_title %}
            <h2>{{ name }}</h2>
        {% endif %}
        {% for slot in slots %}
            {% if display == 'inline' %}
                    {{slot.value}}{% if not forloop.last %},{% endif %}{% spaceless %}
                    {% if forloop.last and next_slot %}
                        {% with item|slots_by_type:next_slot as next_slots %}
                            {% if next_slots %},{% endif %}
                        {% endwith %}
                    {% endif %}
                {% endspaceless %}
            {% else %}
                {{slot.value|markdown}}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

sis_sites/templates/aristotle_mdr/base.html
{% extends request.base_template %}

{% block sis_header %}
{% if request.base_template != 'sis_sites/aristotle_base.html' %}
        
    {% include 'sis_sites/aristotle_scripts.html' %}

    {% block extra_head_scripts %}
        {% comment %}
            Only for scripts that need to be inserted for other special templates
            For example: look ups in supersedes, login, search, etc...
        {% endcomment %}
    {% endblock %}
{% endif %}
{% endblock %}

sis_sites/templates/sis_sites/ocasi/evaluation_plan.html
{% extends "sis_sites/ocasi/evaluation_base.html" %}
{% load markdown_deux_tags %}

{% block nav_evaluation_class %}active{% endblock %}
{% block nav_evaluation_sr_class %} <span class="sr-only">(current)</span>{% endblock %}

{% block title %}{{ flatpage.title }}{% endblock %}

{% block evaluation_nav_plan %}active{% endblock %}

{% block content %}
{{ block.super }}

<div class="row">
    <div class="col-sm-12">
        <div class="title-box">
            <img class="title-box_icon" src="https://logicaloutcomes.github.io/ocasi-theme/img/icons/design_an_evaluation_plan.png" alt="{{ flatpage.title }}">
            <h1 class="title-box_title">{{ flatpage.title }}</h1>
            <p class="title-box_description">
                {{ flatpage.content|markdown }}
            </p>
        </div>
        <br><br>
        {% for content_block in flatpage.contentblock_set.all %}
            {{ content_block.render|safe }}
        {% endfor %}
    </div>
</div>

{% endblock %}

sis_sites/templates/sis_sites/ocasi/review_data_collection_tools.html
{% extends "sis_sites/ocasi/evaluation_base.html" %}
{% load markdown_deux_tags %}

{% block nav_evaluation_class %}active{% endblock %}
{% block nav_evaluation_sr_class %} <span class="sr-only">(current)</span>{% endblock %}

{% block title %}{{ flatpage.title|default:'Review data collection tools' }}{% endblock %}

{% block evaluation_nav_review %}active{% endblock %}

{% block content %}
{{ block.super }}

<div class="row">
    <div class="col-sm-12">
        <div class="title-box">
            <img class="title-box_icon" src="https://logicaloutcomes.github.io/ocasi-theme/img/icons/data_collection.png" alt="Evaluation Plan">
            <h1 class="title-box_title">{{ flatpage.title|default:'Review data collection tools' }}</h1>
            <p class="title-box_description">
                {{ flatpage.content|markdown }}
            </p>
            {% for content_block in flatpage.contentblock_set.all %}
                {{ content_block.render|safe }}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}